travis:
  secure:
    BINSTAR_TOKEN: P10BW+5UH7IDFmloLvM/URp6ulATQ/n3JKJKAxdLo+uDlKQqdayYsJON4BiCVnx8Of9VXj1E1Zbavuvf8mjoktC3uW8iElkHqEfeP4cOYMXHAiFvcWI0Y4ykrH2lUiqTsaoWN8y/ojoLSxhQorUmWih/R0fxwMHpkVFBZs9A9wwjxSMweWHuQFZmba3vMqavf+KNaScn3IH23Kq6XBDUIDPBaI6ZHMCcJJLovnOO3gkjySMvT80ueVWXyvvegYquU3F01WjIHpTuZM4F9TDzLz6iZNpfVQvGdPIBYuMo639+cXGi4x9Du+a0WgChnwiYScwy08SFqcZ8ivbfLwHEylXRreGwNFb85hhAxjBTj//Ukq7XRNbtb0H+rubHUKi1YWszg2t3JEH25eMgZa1rCO1jb7gcRTdaDywAbpnLxKxf3nIyNLuH9HkPZJ9tcoUvMbRoOzKBPIqjS4emG934boV7cQnGL+CTnTdNcMU3YeenfIbNECIYZL8+pRyLooj9UyrT18rQzQw/bdjWF6xfKkAEe3BKzFKhyvMJlXlWBTuXyfkIKxb4XkY1x6CFMpBLh/5DN9CUA+4mrwAr39eOfgek1+DEDFZbiNizENVgW9LriGesPqqWkol/5lx6gSPRGVH0K88JkfQuZ3TRWRzAvIq3wZJQSH0J/6Qc2bd0lYw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
